<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'ISC\\Pro\\' => 8,
            'ISC\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ISC\\Pro\\' => 
        array (
            0 => __DIR__ . '/../..' . '/pro/includes',
        ),
        'ISC\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'ISC\\Analyze_HTML' => __DIR__ . '/../..' . '/includes/analyze-html.php',
        'ISC\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'ISC\\Feedback' => __DIR__ . '/../..' . '/includes/feedback.php',
        'ISC\\Helpers' => __DIR__ . '/../..' . '/includes/helpers.php',
        'ISC\\Indexer' => __DIR__ . '/../..' . '/includes/indexer.php',
        'ISC\\Newsletter' => __DIR__ . '/../..' . '/includes/newsletter.php',
        'ISC\\Plugin' => __DIR__ . '/../..' . '/includes/plugin.php',
        'ISC\\Pro\\Custom_Attribute_Processor' => __DIR__ . '/../..' . '/pro/includes/Custom_Attribute_Processor.php',
        'ISC\\Pro\\IPTC' => __DIR__ . '/../..' . '/pro/includes/IPTC.php',
        'ISC\\Renderer' => __DIR__ . '/../..' . '/includes/renderer.php',
        'ISC\\Renderer\\Caption' => __DIR__ . '/../..' . '/includes/renderer/caption.php',
        'ISC\\Settings' => __DIR__ . '/../..' . '/includes/settings.php',
        'ISC\\Settings\\Section' => __DIR__ . '/../..' . '/includes/settings/section.php',
        'ISC\\Settings\\Sections\\Caption' => __DIR__ . '/../..' . '/includes/settings/sections/caption.php',
        'ISC\\Settings\\Sections\\Global_List' => __DIR__ . '/../..' . '/includes/settings/sections/global-list.php',
        'ISC\\Settings\\Sections\\Licenses' => __DIR__ . '/../..' . '/includes/settings/sections/licenses.php',
        'ISC\\Settings\\Sections\\Miscellaneous' => __DIR__ . '/../..' . '/includes/settings/sections/miscellaneous.php',
        'ISC\\Settings\\Sections\\Newsletter' => __DIR__ . '/../..' . '/includes/settings/sections/newsletter.php',
        'ISC\\Settings\\Sections\\Page_List' => __DIR__ . '/../..' . '/includes/settings/sections/page-list.php',
        'ISC\\Standard_Source' => __DIR__ . '/../..' . '/includes/standard-source.php',
        'ISC\\Unused_Images' => __DIR__ . '/../..' . '/includes/unused-images.php',
        'ISC\\User' => __DIR__ . '/../..' . '/includes/user.php',
        'ISC_Admin' => __DIR__ . '/../..' . '/admin/admin.php',
        'ISC_Block_Options' => __DIR__ . '/../..' . '/includes/block-options/block-options.php',
        'ISC_Class' => __DIR__ . '/../..' . '/includes/isc.class.php',
        'ISC_Log' => __DIR__ . '/../..' . '/includes/log.php',
        'ISC_Model' => __DIR__ . '/../..' . '/includes/model.php',
        'ISC_Public' => __DIR__ . '/../..' . '/public/public.php',
        'ISC_Storage_Model' => __DIR__ . '/../..' . '/includes/storage-model.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b::$classMap;

        }, null, ClassLoader::class);
    }
}
