<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'ISC\\Pro\\' => 8,
            'ISC\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ISC\\Pro\\' => 
        array (
            0 => __DIR__ . '/../..' . '/pro/includes',
        ),
        'ISC\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'ISC\\Admin' => __DIR__ . '/../..' . '/admin/admin.php',
        'ISC\\Admin\\Admin_Ajax' => __DIR__ . '/../..' . '/admin/includes/ajax.php',
        'ISC\\Admin\\Admin_Scripts' => __DIR__ . '/../..' . '/admin/includes/scripts.php',
        'ISC\\Admin\\Media_Library_Checks' => __DIR__ . '/../..' . '/admin/includes/media-library-checks.php',
        'ISC\\Admin\\Media_Library_Filter' => __DIR__ . '/../..' . '/admin/includes/media-library-filter.php',
        'ISC\\Admin_Utils' => __DIR__ . '/../..' . '/admin/utils.php',
        'ISC\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'ISC\\Feedback' => __DIR__ . '/../..' . '/includes/feedback.php',
        'ISC\\Helpers' => __DIR__ . '/../..' . '/includes/helpers.php',
        'ISC\\Image_Sources\\Admin' => __DIR__ . '/../..' . '/includes/image-sources/admin.php',
        'ISC\\Image_Sources\\Admin_Ajax' => __DIR__ . '/../..' . '/includes/image-sources/admin/ajax.php',
        'ISC\\Image_Sources\\Admin_Fields' => __DIR__ . '/../..' . '/includes/image-sources/admin/fields.php',
        'ISC\\Image_Sources\\Admin_Media_Library_Filters' => __DIR__ . '/../..' . '/includes/image-sources/admin/media-library-filters.php',
        'ISC\\Image_Sources\\Admin_Menu' => __DIR__ . '/../..' . '/includes/image-sources/admin/menu.php',
        'ISC\\Image_Sources\\Admin_Notices' => __DIR__ . '/../..' . '/includes/image-sources/admin/notices.php',
        'ISC\\Image_Sources\\Analyze_HTML' => __DIR__ . '/../..' . '/includes/image-sources/analyze-html.php',
        'ISC\\Image_Sources\\Image_Sources' => __DIR__ . '/../..' . '/includes/image-sources/image-sources.php',
        'ISC\\Image_Sources\\Image_Sources_Admin_Scripts' => __DIR__ . '/../..' . '/includes/image-sources/admin/scripts.php',
        'ISC\\Image_Sources\\Post_Meta\\Image_Posts_Meta' => __DIR__ . '/../..' . '/includes/image-sources/Post_Meta/Image_Posts_Meta.php',
        'ISC\\Image_Sources\\Post_Meta\\Post_Images_Meta' => __DIR__ . '/../..' . '/includes/image-sources/Post_Meta/Post_Images_Meta.php',
        'ISC\\Image_Sources\\Renderer' => __DIR__ . '/../..' . '/includes/image-sources/renderer.php',
        'ISC\\Image_Sources\\Renderer\\Caption' => __DIR__ . '/../..' . '/includes/image-sources/renderer/caption.php',
        'ISC\\Image_Sources\\Renderer\\Global_List' => __DIR__ . '/../..' . '/includes/image-sources/renderer/global-list.php',
        'ISC\\Image_Sources\\Renderer\\Image_Source_String' => __DIR__ . '/../..' . '/includes/image-sources/renderer/image-source-string.php',
        'ISC\\Image_Sources\\Utils' => __DIR__ . '/../..' . '/includes/image-sources/utils.php',
        'ISC\\Indexer' => __DIR__ . '/../..' . '/includes/indexer.php',
        'ISC\\Media_Type_Checker' => __DIR__ . '/../..' . '/includes/media-type-checker.php',
        'ISC\\Newsletter' => __DIR__ . '/../..' . '/includes/newsletter.php',
        'ISC\\Options' => __DIR__ . '/../..' . '/includes/options.php',
        'ISC\\Plugin' => __DIR__ . '/../..' . '/includes/plugin.php',
        'ISC\\Pro\\Custom_Attribute_Processor' => __DIR__ . '/../..' . '/pro/includes/Custom_Attribute_Processor.php',
        'ISC\\Pro\\IPTC' => __DIR__ . '/../..' . '/pro/includes/IPTC.php',
        'ISC\\Pro\\List_Layout_Details' => __DIR__ . '/../..' . '/pro/includes/List_Layout_Details.php',
        'ISC\\Pro\\Unused_Images\\Admin\\Appearances_Column' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Admin/Appearances_Column.php',
        'ISC\\Pro\\Unused_Images\\Admin\\Unused_Images' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Admin/Unused_Images.php',
        'ISC\\Pro\\Unused_Images\\Admin\\Unused_Images_List_Table' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Admin/Unused_Images_List_Table.php',
        'ISC\\Pro\\Unused_Images\\Content_Scan\\Content_Scan' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Content_Scan/Content_Scan.php',
        'ISC\\Pro\\Unused_Images\\Content_Scan\\Content_Scan_Admin' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Content_Scan/Content_Scan_Admin.php',
        'ISC\\Pro\\Unused_Images\\Content_Scan\\Content_Scan_Public' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Content_Scan/Content_Scan_Public.php',
        'ISC\\Pro\\Unused_Images\\Content_Scan\\Content_Scan_Run' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Content_Scan/Content_Scan_Run.php',
        'ISC\\Pro\\Unused_Images\\Content_Scan\\Content_Scan_Runner' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Content_Scan/Content_Scan_Runner.php',
        'ISC\\Pro\\Unused_Images\\Content_Scan\\Content_Scan_Table' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Content_Scan/Content_Scan_Table.php',
        'ISC\\Pro\\Unused_Images\\Database_Scan\\Database_Check_Model' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Database_Scan/Database_Check_Model.php',
        'ISC\\Pro\\Unused_Images\\Database_Scan\\Database_Scan' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Database_Scan/Database_Scan.php',
        'ISC\\Pro\\Unused_Images\\Scanner\\Batch_Size_Calculator' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Scanner/Batch_Size_Calculator.php',
        'ISC\\Pro\\Unused_Images\\Scanner\\Scanner_Admin' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Scanner/Scanner_Admin.php',
        'ISC\\Pro\\Unused_Images\\Scanner\\Scanner_Log' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Scanner/Scanner_Log.php',
        'ISC\\Pro\\Unused_Images\\Scanner\\Scanner_Orchestrator' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Scanner/Scanner_Orchestrator.php',
        'ISC\\Pro\\Unused_Images\\Scanner\\Scanner_Stats' => __DIR__ . '/../..' . '/pro/includes/Unused_Images/Scanner/Scanner_Stats.php',
        'ISC\\Settings' => __DIR__ . '/../..' . '/includes/settings.php',
        'ISC\\Settings\\Section' => __DIR__ . '/../..' . '/includes/settings/section.php',
        'ISC\\Settings\\Sections\\Caption' => __DIR__ . '/../..' . '/includes/settings/sections/caption.php',
        'ISC\\Settings\\Sections\\Global_List' => __DIR__ . '/../..' . '/includes/settings/sections/global-list.php',
        'ISC\\Settings\\Sections\\Licenses' => __DIR__ . '/../..' . '/includes/settings/sections/licenses.php',
        'ISC\\Settings\\Sections\\Miscellaneous' => __DIR__ . '/../..' . '/includes/settings/sections/miscellaneous.php',
        'ISC\\Settings\\Sections\\Newsletter' => __DIR__ . '/../..' . '/includes/settings/sections/newsletter.php',
        'ISC\\Settings\\Sections\\Page_List' => __DIR__ . '/../..' . '/includes/settings/sections/page-list.php',
        'ISC\\Settings\\Sections\\Plugin_Options' => __DIR__ . '/../..' . '/includes/settings/sections/plugin-options.php',
        'ISC\\Standard_Source' => __DIR__ . '/../..' . '/includes/standard-source.php',
        'ISC\\Unused_Images' => __DIR__ . '/../..' . '/includes/unused-images.php',
        'ISC\\User' => __DIR__ . '/../..' . '/includes/user.php',
        'ISC_Block_Options' => __DIR__ . '/../..' . '/includes/block-options/block-options.php',
        'ISC_Class' => __DIR__ . '/../..' . '/includes/isc.class.php',
        'ISC_Log' => __DIR__ . '/../..' . '/includes/log.php',
        'ISC_Model' => __DIR__ . '/../..' . '/includes/model.php',
        'ISC_Public' => __DIR__ . '/../..' . '/public/public.php',
        'ISC_Storage_Model' => __DIR__ . '/../..' . '/includes/storage-model.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b::$classMap;

        }, null, ClassLoader::class);
    }
}
