<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ISC\\Pro\\' => array($baseDir . '/pro/includes'),
    'ISC\\' => array($baseDir . '/includes'),
);
