<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'ISC\\Analyze_HTML' => $baseDir . '/includes/analyze-html.php',
    'ISC\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'ISC\\Helpers' => $baseDir . '/includes/helpers.php',
    'ISC\\Newsletter' => $baseDir . '/includes/newsletter.php',
    'ISC\\Pro\\IPTC' => $baseDir . '/pro/includes/IPTC.php',
    'ISC\\Settings\\Newsletter' => $baseDir . '/includes/settings/newsletter.php',
    'ISC\\Standard_Source' => $baseDir . '/includes/standard-source.php',
    'ISC\\Unused_Images' => $baseDir . '/includes/unused-images.php',
    'ISC_Admin' => $baseDir . '/admin/admin.php',
    'ISC_Block_Options' => $baseDir . '/includes/block-options/block-options.php',
    'ISC_Class' => $baseDir . '/includes/isc.class.php',
    'ISC_Log' => $baseDir . '/includes/log.php',
    'ISC_Model' => $baseDir . '/includes/model.php',
    'ISC_Public' => $baseDir . '/public/public.php',
    'ISC_Storage_Model' => $baseDir . '/includes/storage-model.php',
);
