<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'ISC\\Analyze_HTML' => $baseDir . '/includes/analyze-html.php',
    'ISC\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'ISC\\Feedback' => $baseDir . '/includes/feedback.php',
    'ISC\\Helpers' => $baseDir . '/includes/helpers.php',
    'ISC\\Newsletter' => $baseDir . '/includes/newsletter.php',
    'ISC\\Plugin' => $baseDir . '/includes/plugin.php',
    'ISC\\Pro\\IPTC' => $baseDir . '/pro/includes/IPTC.php',
    'ISC\\Renderer' => $baseDir . '/includes/renderer.php',
    'ISC\\Renderer\\Caption' => $baseDir . '/includes/renderer/caption.php',
    'ISC\\Settings' => $baseDir . '/includes/settings.php',
    'ISC\\Settings\\Section' => $baseDir . '/includes/settings/section.php',
    'ISC\\Settings\\Sections\\Caption' => $baseDir . '/includes/settings/sections/caption.php',
    'ISC\\Settings\\Sections\\Global_List' => $baseDir . '/includes/settings/sections/global-list.php',
    'ISC\\Settings\\Sections\\Licenses' => $baseDir . '/includes/settings/sections/licenses.php',
    'ISC\\Settings\\Sections\\Miscellaneous' => $baseDir . '/includes/settings/sections/miscellaneous.php',
    'ISC\\Settings\\Sections\\Newsletter' => $baseDir . '/includes/settings/sections/newsletter.php',
    'ISC\\Settings\\Sections\\Page_List' => $baseDir . '/includes/settings/sections/page-list.php',
    'ISC\\Standard_Source' => $baseDir . '/includes/standard-source.php',
    'ISC\\Unused_Images' => $baseDir . '/includes/unused-images.php',
    'ISC\\User' => $baseDir . '/includes/user.php',
    'ISC_Admin' => $baseDir . '/admin/admin.php',
    'ISC_Block_Options' => $baseDir . '/includes/block-options/block-options.php',
    'ISC_Class' => $baseDir . '/includes/isc.class.php',
    'ISC_Log' => $baseDir . '/includes/log.php',
    'ISC_Model' => $baseDir . '/includes/model.php',
    'ISC_Public' => $baseDir . '/public/public.php',
    'ISC_Storage_Model' => $baseDir . '/includes/storage-model.php',
);
