<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'ISC\\Pro\\' => 8,
            'ISC\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ISC\\Pro\\' => 
        array (
            0 => __DIR__ . '/../..' . '/pro/includes',
        ),
        'ISC\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'ISC\\Analyze_HTML' => __DIR__ . '/../..' . '/includes/analyze-html.php',
        'ISC\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'ISC\\Pro\\IPTC' => __DIR__ . '/../..' . '/pro/includes/IPTC.php',
        'ISC\\Standard_Source' => __DIR__ . '/../..' . '/includes/standard-source.php',
        'ISC\\Unused_Images' => __DIR__ . '/../..' . '/includes/unused-images.php',
        'ISC_Admin' => __DIR__ . '/../..' . '/admin/admin.php',
        'ISC_Block_Options' => __DIR__ . '/../..' . '/includes/block-options/block-options.php',
        'ISC_Class' => __DIR__ . '/../..' . '/includes/isc.class.php',
        'ISC_Log' => __DIR__ . '/../..' . '/includes/log.php',
        'ISC_Model' => __DIR__ . '/../..' . '/includes/model.php',
        'ISC_Public' => __DIR__ . '/../..' . '/public/public.php',
        'ISC_Storage_Model' => __DIR__ . '/../..' . '/includes/storage-model.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitdb72a6bac11cb0e6b971811c93d09a9b::$classMap;

        }, null, ClassLoader::class);
    }
}
